### ISSUE TITLE
Better diffs of base and series

### ISSUE THREAD

**Issue by joshtriplett** [git-series/git-series#2]
Currently, the diffs of `series` and `base` shown in `git series log -p` just show the old and new commit hashes.  The diff for `base` should include the commit summary for both commits, and possibly decorations.  The diff of `series` should show some useful summary of how the patch series has changed.

Potentially useful information for diffs of series:
- Diff of a list of patch subjects (`git log --oneline` output without the hashes).  Useful to see patch reorganization.
- Diff of full commit messages.
- Diff of full commits with patches included, with rename detection turned on to notice patch reordering.  (Helpful if you don't mind reading diffs-of-diffs.)
- Overall diff of final git trees.  (For instance, when refactoring or rebasing patches, it helps to know what has changed in the whole series.  Less useful if you've rebased the series.)
- Something like `git-cherry`.  This depends on `patch-id`, though, which changes when the patch changes at all.

Based on discussions with users, the default will be diffs of full commits with patches included.  There will also be a second option to provide the overall diff of the final git trees.

**Comment by knuto** [comment]
A command I keep using during  a set of rebases is 'git show-branch' listing shas before and after rebase. Maybe you can use that for the simplest form of git series diff ?

**Comment by kergoth** [comment]
Check out [git-tbdiff](https://github.com/trast/tbdiff) - great tool for comparing topic branches. Shows what commits were added/removed, and for modified commits shows an interdiff. I think if git series log -p showed that, it'd be ideal. Example output:
```
1:  1b5c6b2 < -:  ------- bb.fetch: handle checksums consistently for mirrors
2:  a84ad5b < -:  ------- bb.fetch: don't remove the clone when an update fails
3:  9cc2320 < -:  ------- bb.fetch.git: remove leading '.' from gitsrcname
6:  76d57e1 = 1:  9484157 bb.fetch: simplify mirror tarball handling in try_mirror_url
7:  92c2c8b ! 2:  5a011a2 bb.fetch: support ud.mirrortarballs
    @@ -2,7 +2,7 @@

         bb.fetch: support ud.mirrortarballs

    -    This lets us support multiple types of mirror tarballs. The main use case for
    +    This lets us support multiple mirror tarball filenames. The main use case for
         this at this time is for git, to be able to support both shallow and full git
         mirror tarballs.
```

**Comment by joshtriplett** [comment]
That looks perfect, thanks!  And tbdiff's README has a clear explanation of the algorithm, too.

The [munkres](https://crates.io/crates/munkres) crate appears to handle the assignment problem.

**Comment by kergoth** [comment]
In case anyone wants something to hold them over, just did a quick and dirty python script that does a series log with tbdiffs, calling out to git-tbdiff to do the work. https://gist.github.com/kergoth/a3b0bdcadf4e314bc60c350b76f112a2 is the script, https://gist.github.com/kergoth/c9cb0c0e59b140789f86be84752a99fc shows example output from it for one of my patch series.

**Comment by jacob-keller** [comment]
I have an alternative proposal that I came up with after seeing a series of suggestions on StackOverflow regarding how to show the difference between two series. So say you have series v1 and series v2. Lets say you've done a rebase and thus update the base pointer.

You can't just

    git diff v1 v2

Since this will show all the differences due to the rebase, which is really not what people actually want.

One way to think about what the difference is is to think something like v2 is the result of

    git checkout v1
    git merge <new base>
    # make the tree look like v2
    git commit

Thus, one way to obtain this difference is to do something like this:

    git show --pretty="" $(git commit-tree v2^{tree} -p v1 -p base -m "message")

Essentially we're showing the combined diff format of the merge of base into v1 plus any necessary modifications ot make the result look like v2.

This produces output sort of like the following:

    diff --cc src/CORE/i40e_main.c
    index 151fa52b92bf,745229e720e1..44d169f569dd
    --- a/src/CORE/i40e_main.c
    +++ b/src/CORE/i40e_main.c
    @@@ -1862,8 -1766,8 +1863,8 @@@ struct i40e_mac_filter *i40e_add_filter
       * ANOTHER NOTE: This function MUST be called from within the context of
       * the "safe" variants of any list iterators, e.g. list_for_each_entry_safe()
       * instead of list_for_each_entry().
    -  */
    +  **/
     -static void __i40e_del_filter(struct i40e_vsi *vsi, struct i40e_mac_filter *f)
     +void __i40e_del_filter(struct i40e_vsi *vsi, struct i40e_mac_filter *f)
      {
            if (!f)
                    return;


Currently it does not appear possible to simply produce the diff directly, but I don't see why not, so I am investigating what it would take to allow diff to be able to produce this without the need for the git-commit-tree step.

Essentially this is a robust way to produce a interdifference between two versions.

I don't think this is a replacement for the tbdiff code, but I do think it might be something tbdiff could use to help reduce the clutter of showing all the stuff that a series got rebased onto, which happens when you change the base pointer, and usually isn't what people care about.

What they *do* care about and what *is* shown is the conflicts required to make that rebase successful.

**Comment by jacob-keller** [comment]
It turns out at least with git diff, you can generate this via something like

git diff <new> <old> <base>

Maybe we can make that an option for when showing the series?

**Comment by joshtriplett** [comment]
git-series 0.9.0 now provides a series diff, via `git series diff`, `git series log -p`, and `git series commit -v`.
