### ISSUE TITLE
git series rebase -i gives: no such file or directory error on file rebased-merge/stopped-sha

### ISSUE THREAD

**Issue by davidker** [git-series/git-series#38]
I just did a git series rebase -i to pull 3 patches from the series and everything appears to be working fine, but I get the following message on the console: 

<ebase-merge.eqRWLxvVEHIe/git-rebase-todo" 31L, 1663C written
Checking out files: 5/5
**cat: /home/kershnda/kernel/master/unisys/.git/rebase-merge/stopped-sha: No such file or directory**
Successfully rebased and updated detached HEAD.

Not sure what that message is trying to tell me.

**Comment by joshtriplett** [comment]
That looks like a bug in the git-rebase shell script, fixed in more recent versions of git.  What version of git do you have installed on that system?

Some versions of git's interactive rebase would unconditionally expect the `stopped-sha` file to exist in the state directory, rather than checking for it to exist first.

**Comment by davidker** [comment]
My version of git is 1.9.1, guess it is a little out of date. Thanks for looking at it. 

David Kershner

**Comment by joshtriplett** [comment]
That's odd; that version of git should have the fix to `git-rebase--interactive.sh`.
